### ISSUE TITLE
Simple Parallel does not trigger on rising edge correctly

### ISSUE THREAD

**Issue by maynardephd** [saleae/simple-parallel-analyzer#10]
Running the latest everything (just received my device a week ago). Running the Simple parallel analyzer and I noticed that it is not triggering on the rising edge of the clock. Falling edge is fine - but the rising edge is clearly incorrect. Doesn't look like I can add a picture of my screen.

This means that the address being decoded from other lines is invariably incorrect making this analyzer less than useful for this task.

**Comment by timreyes** [comment]
Thanks for reporting this! I'm assuming this post was you as well?
https://discuss.saleae.com/t/simple-parallel-analyzer-does-not-trigger-properly/2049

I'll chat with you in that forum post for now and will close this Issue Post. I'll re-open this again in case we confirm this is a bug in our Simple Parallel analyzer.

**Comment by maynardephd** [comment]
Yes. Sorry about that. I found the GitHub repo first. I’ll be happy to provide any info you need.Cheers,EdSent from my iPhoneOn Jan 18, 2023, at 3:18 PM, timreyes ***@***.***> wrote:﻿
Closed #10 as completed.
