### ISSUE TITLE
Failed to load custom analyzer (simple-parallel-analyzer\build\bin\Analyzer.dll): Loaded library does not have required functions

### ISSUE THREAD

**Issue by ChrisIdema** [saleae/simple-parallel-analyzer#9]
I successfully build the analyzer. I get the following error when adding the bin folder to Logic2 and restarting it:
```
Failed to Load Custom Analyzer
Failed to load custom analyzer (simple-parallel-analyzer\build\bin\Analyzer.dll): Loaded library does not have required functions
```

**Comment by timreyes** [comment]
Sorry for the confusion! The correct dll file will be located in the "build" folder. It should be called simple_parallel_analyzer.dll. Hope that solves it!

**Comment by ChrisIdema** [comment]
Thanks! I looked in the wrong folder. I followed the instructions from https://support.saleae.com/faq/technical-faq/setting-up-developer-directory but they have a different location and simply say 

> Browse to the location where **_the .dll_**, .so, or .dylib analyzer library is stored

 But in this case there are multiple locations with a dll. After renaming "Simple Parallel" in both locations I got it to work. Thanks!

**Comment by timreyes** [comment]
Ah, glad to hear you got that to work! Sorry about the documentation not being clear. I'll get that on the backlog to fix.
